keyconfig_version = (4, 1, 23)
keyconfig_data = \
[("Weight Paint",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("paint.weight_paint", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("paint.weight_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.weight_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SMOOTH'),
       ],
      },
     ),
    ("paint.weight_sample", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("paint.weight_sample_group", {"type": 'X', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("paint.weight_gradient",
     {"type": 'A', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("type", 'RADIAL'),
       ],
      },
     ),
    ("paint.weight_gradient",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LINEAR'),
       ],
      },
     ),
    ("paint.weight_set", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.weight_paint.brush.weight'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.weight'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_weight'),
       ("rotation_path", 'tool_settings.weight_paint.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.weight_paint.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.weight_paint.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.vertex_paint.brush.stroke_method'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'weight_paint_object.data.use_paint_mask'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'weight_paint_object.data.use_paint_mask_vertex'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'weight_paint_object.data.use_paint_bone_selection'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.weight_paint.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_wpaint_vgroup_lock_pie'),
       ],
      },
     ),
    ("paint.face_vert_reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_paint_weight_context_menu'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_paint_weight_context_menu'),
       ],
      },
     ),
    ("view3d.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.bone_select_menu", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
